MyPortfolio/Models/Projeto.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyPortfolio.Models
{
    public class Projeto
    {
        [Key]
        public string ID { get; set; }
        [Required]
        [MaxLength(100)]
        public string Titulo { get; set; }
        [Required]
        [MaxLength(500)]
        public string Descricao { get; set; }
        [Required]
        [MaxLength(100)]
        public string Tipo { get; set; }
        [Required]
        [MaxLength(100)]
        public string FrontEnd { get; set; }
        [Required]
        [MaxLength(100)]
        public string BackEnd { get; set; }
        [Required]
        [MaxLength(100)]
        public string BancoDados { get; set; }
        [MaxLength(40)]
        public string ImgBackground { get; set; }
        [MaxLength(40)]
        public string Img01 { get; set; }
        [MaxLength(40)]
        public string Img02 { get; set; }
        [MaxLength(150)]
        public string GitUrl { get; set; }
        [MaxLength(150)]
        public string SiteUrl { get; set; }

        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}

MyPortfolio/Models/ViewModels/Projetos/ProjetoCreateEditViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyPortfolio.Models.ViewModels.Projetos
{
    public class ProjetoCreateEditViewModel
    {
        public string ID { get; set; }

        [Required(ErrorMessage = "Preencher o campo Título")]
        [MaxLength(100, ErrorMessage = "No máximo 100 caracteres")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Preencher o campo Descrição")]
        [MaxLength(500, ErrorMessage = "No máximo 500 caracteres")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "Selecionar à Categoria")]
        public string Tipo { get; set; }

        public List<SelectListItem> CatList { get; set; }

        [Required(ErrorMessage = "Selecionar a tecnologia front-end")]
        public string FrontEnd { get; set; }

        public List<SelectListItem> FEList { get; set; }

        [Required(ErrorMessage = "Selecionar a tecnologia back-end")]
        public string BackEnd { get; set; }

        public List<SelectListItem> BEList { get; set; }

        [Required(ErrorMessage = "Selecionar o Banco de dados")]
        public string BancoDados { get; set; }

        public List<SelectListItem> DBList { get; set; }

        [Required(ErrorMessage = "Selecionar imagem de background")]
        public IFormFile ImgBackground { get; set; }

        public string BackgroundPath { get; set; }

        [Required(ErrorMessage = "Selecionar imagem 01")]
        public IFormFile Img01 { get; set; }

        public string Img01Path { get; set; }

        [Required(ErrorMessage = "Selecionar imagem 02")]
        public IFormFile Img02 { get; set; }

        public string Img02Path { get; set; }
        public string GitUrl { get; set; }
        public string SiteUrl { get; set; }

    }
}

MyPortfolio/Models/ViewModels/Projetos/ProjetoIndexViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MyPortfolio.Helpers;
using MyPortfolio.Models;
using System.Collections.Generic;

namespace MyPortfolio.Models.ViewModels.Projetos
{
    public class ProjetoIndexViewModel
    {
        public Paginacao<Projeto> PagedProjetos { set; get; }
        public List<SelectListItem> ProjetoFiltro { get; set; }
        public string FiltroId { get; set; }
    }
}

MyPortfolio/Models/ViewModels/Projetos/UpdateImageAjaxViewModel.cs
using Microsoft.AspNetCore.Http;

namespace MyPortfolio.Models.ViewModels.Projetos
{
    public class UpdateImageAjaxViewModel
    {
        public string ProjetoId { get; set; }
        public string Tipo { get; set; }
        public IFormFile File { get; set; }
    }
}

MyPortfolio/Controllers/ProjetoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MyPortfolio.Data;
using MyPortfolio.Helpers;
using MyPortfolio.Models;
using MyPortfolio.Models.ViewModels.Projetos;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MyPortfolio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProjetoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IWebHostEnvironment _hostingEnvironment;
        private IConfiguration _configuration;
        private readonly FileManager _fileManager;

        public ProjetoController(ApplicationDbContext context,
            IWebHostEnvironment environment,
            IConfiguration configuration,
            FileManager fileManager)
        {
            _context = context;
            _hostingEnvironment = environment;
            _configuration = configuration;
            _fileManager = fileManager;
        }

        #region Index
        public async Task<IActionResult> Index()
        {
            var projetos = from p in _context.Projetos
                           select p;

            //... Passa a query proveniente dos filtros e paginação
            var pagination = await Paginacao<Projeto>.Pagination(projetos.AsNoTracking(), 1, 15);

            var vm = new ProjetoIndexViewModel
            {
                ProjetoFiltro = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Título", Value = "1" },
                    new SelectListItem { Text = "Categoria", Value = "2" }

                },
                PagedProjetos = pagination
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string sortOrder,
           string currentFilter,
           string searchString,
           ProjetoIndexViewModel model,
           int? pageNumber,
           int pageSize = 15)
        {
            var projetos = from p in _context.Projetos
                           select p;

            //... Se foi enviado texto no campo de busca
            if (!string.IsNullOrEmpty(searchString))
            {
                //... Set up da página para o iníceio
                pageNumber = 1;

                //... Busca pelo usuário como padrão se não encontrar busca pelo e - mail
                switch (model.FiltroId)
                {
                    case "1":
                        projetos = projetos.Where(s => s.Titulo.ToUpper().Contains(searchString.ToUpper()));
                        break;

                    case "2":
                        projetos = projetos.Where(s => s.Tipo.ToUpper().Contains(searchString.ToUpper()));
                        break;
                }
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            //... Passa a query proveniente dos filtros e paginação
            var pagination = await Paginacao<Projeto>.Pagination(projetos.AsNoTracking(), pageNumber ?? 1, pageSize);

            var vm = new ProjetoIndexViewModel
            {
                PagedProjetos = pagination,
                ProjetoFiltro = model.ProjetoFiltro
            };

            return View(vm);
        }
        #endregion

        #region Criar
        public IActionResult Create()
        {
            var vm = new ProjetoCreateEditViewModel
            {
                FEList = GetFE().ToList(),
                BEList = GetBE().ToList(),
                DBList = GetDatabases().ToList(),
                CatList = GetCategories().ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProjetoCreateEditViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                vm.FEList = GetFE().ToList();
                vm.BEList = GetBE().ToList();
                vm.DBList = GetDatabases().ToList();
                vm.CatList = GetCategories().ToList();
                return View(vm);
            }

            //Caminho raiz para os arquivos
            var rootPath = _hostingEnvironment.WebRootPath;
            //Caminho para o diretório padrão
            var pathToDir = rootPath + _configuration["File:DefaultFolder"];
            //Nome único para o arquivo e concat da extensão 
            var imgBg = $@"{Guid.NewGuid()}" + Path.GetExtension(vm.ImgBackground.FileName);
            var img01 = $@"{Guid.NewGuid()}" + Path.GetExtension(vm.Img01.FileName);
            var img02 = $@"{Guid.NewGuid()}" + Path.GetExtension(vm.Img02.FileName);

            //. . . Salva os arquivos fisicamente
            _fileManager.AddFile(Path.Combine(pathToDir, imgBg), vm.ImgBackground);
            _fileManager.AddFile(Path.Combine(pathToDir, img01), vm.ImgBackground);
            _fileManager.AddFile(Path.Combine(pathToDir, img02), vm.ImgBackground);

            try
            {
                var project = new Projeto
                {
                    ID = Guid.NewGuid().ToString(),
                    Titulo = vm.Titulo,
                    Tipo = vm.Tipo,
                    BancoDados = vm.BancoDados,
                    BackEnd = vm.BackEnd,
                    FrontEnd = vm.FrontEnd,
                    Descricao = vm.Descricao,
                    ImgBackground = imgBg,
                    Img01 = img01,
                    Img02 = img02,
                    GitUrl = vm.GitUrl,
                    SiteUrl = vm.SiteUrl,
                    CreatedOn = DateTime.Now
                };

                await _context.Projetos.AddAsync(project);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                throw new Exception("Erro: " + ex.Message + " / " + ex.InnerException);
            }

            return RedirectToAction("Index");
        }
        #endregion

        #region Detalhes
        public async Task<IActionResult> Details(string Id)
        {
            var project = await _context.Projetos.FindAsync(Id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }
        #endregion

        #region Editar
        public async Task<IActionResult> Edit(string Id)
        {
            var projeto = await _context.Projetos
                .AsNoTracking()
                .FirstOrDefaultAsync(p => p.ID == Id);

            var vm = new ProjetoCreateEditViewModel
            {
                ID = Id,
                Titulo = projeto.Titulo,
                Tipo = projeto.Tipo,
                BancoDados = projeto.BancoDados,
                BackEnd = projeto.BackEnd,
                FrontEnd = projeto.FrontEnd,
                Descricao = projeto.Descricao,
                GitUrl = projeto.GitUrl,
                SiteUrl = projeto.SiteUrl,
                BackgroundPath = $@"{_configuration["File:DefaultFolder"]}" + projeto.ImgBackground,
                Img01Path = $@"{_configuration["File:DefaultFolder"]}" + projeto.Img01,
                Img02Path = $@"{_configuration["File:DefaultFolder"]}" + projeto.Img02,
                FEList = GetFE().ToList(),
                BEList = GetBE().ToList(),
                DBList = GetDatabases().ToList(),
                CatList = GetCategories().ToList()
            };

            if (projeto == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProject(string id)
        {
            var projeto = await _context.Projetos
                .FirstOrDefaultAsync(p => p.ID == id);

            projeto.UpdatedOn = DateTime.UtcNow;

            if (await TryUpdateModelAsync<Projeto>(projeto, "",
                c => c.Titulo,
                c => c.Tipo,
                c => c.BackEnd,
                c => c.FrontEnd,
                c => c.BancoDados,
                c => c.GitUrl,
                c => c.SiteUrl,
                c => c.Descricao))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", "Erro ao atualizar projeto: " + ex.InnerException + " : " + ex.Message);
                }
            }

            return View(projeto);
        }

        /// <summary>
        /// Atualiza as imagens do projeto via AJAX
        /// </summary>
        /// <param name="ProjetoId">ID do projeto</param>
        /// <param name="Tipo">Tipos: ImgBackground, Img01 e Img02</param>
        /// <param name="File">Arquivo físico selecionado pelo usuário</param>
        [HttpPost]
        public async Task<IActionResult> UpdateImageAjax(UpdateImageAjaxViewModel vm)
        {
            if (vm.File == null)
            {
                return NotFound();
            }

            //Busca o projeto
            var projeto = await _context.Projetos.FindAsync(vm.ProjetoId);
            //Variáveis do sistema
            var fileName = string.Empty;
            var fullPath = string.Empty;
            var tipoFile = string.Empty;
            //Caminho raiz para os arquivos
            var rootPath = _hostingEnvironment.WebRootPath;
            var defaultPath = _configuration["File:DefaultFolder"];
            var folderPath = rootPath + defaultPath;

            //Tipo do arquivo
            // *imgBackground: Imagem de background

MyPortfolio/Views/Projeto/Delete.cshtml
@model Projeto
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-header no-margin-bottom">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Projetos</h2>
    </div>
</div>
<div class="container-fluid">
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index">Projeto Listar</a></li>
        <li class="breadcrumb-item active">Excluir projeto</li>
    </ul>
</div>
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="block">
                    <div class="title">
                    <strong class="d-block text-center">
                        <i class="fa fa-warning fa-2x text-center mr-2"></i>Deseja excluir o projeto: '@Model.Titulo'</strong>
                    </div>
                    <div class="block-body">
                        <form asp-action="Delete"
                              asp-controller="Projeto"
                              method="post"
                              class="form-horizontal">
                            <div class="block text-center">
                                @*<a class="btn btn-danger"
                                   asp-action="Delete"
                                   asp-route-Id="@Model.ID">Sim</a>*@

                                <button class="btn btn-danger" type="submit">Sim</button>

                                <a class="btn btn-light"
                                   asp-action="Index">Não</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MyPortfolio/Views/Projeto/Details.cshtml
@model Projeto
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-header no-margin-bottom">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Projetos</h2>
    </div>
</div>
<div class="container-fluid">
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index">Projeto Listar</a></li>
        <li class="breadcrumb-item active">Informações do projeto</li>
    </ul>
</div>
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="block">
                    <div class="title"><strong class="d-block">Informações principais</strong></div>
                    <div class="block-body">
                        <form class="form-horizontal">
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Título</label>
                                <div class="col-sm-9">
                                    <input value="@Model.Titulo" disabled class="form-control form-control-success">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Categoria</label>
                                <div class="col-sm-9">
                                    <input value="@Model.Tipo" disabled class="form-control form-control-success">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Back-end</label>
                                <div class="col-sm-9">
                                    <input value="@Model.BackEnd" disabled class="form-control form-control-success">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Front-end</label>
                                <div class="col-sm-9">
                                    <input value="@Model.FrontEnd" disabled class="form-control form-control-success">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Banco de dados</label>
                                <div class="col-sm-9">
                                    <input value="@Model.BancoDados" disabled class="form-control form-control-success">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Descrição</label>
                                <div class="col-sm-9">
                                    <textarea disabled class="form-control" rows="4">@Model.Descricao</textarea>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card">
                    <a href="~/img/Uploads/@Model.ImgBackground" data-lightbox="gallery" data-title="Imagem de background">
                        <img src="~/img/Uploads/@Model.ImgBackground" alt="Imagem de background" class="img-small">
                    </a>
                    <div class="card-body">
                        <h6 class="card-title mb-1">Imagem 01</h6>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card">
                    <a href="~/img/Uploads/@Model.Img01" data-lightbox="gallery" data-title="Imagem 01">
                        <img src="~/img/Uploads/@Model.Img01" alt="Imagem 01" class="img-small">
                    </a>
                    <div class="card-body">
                        <h6 class="card-title mb-1">Imagem 02</h6>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card">
                    <a href="~/img/Uploads/@Model.Img02" data-lightbox="gallery" data-title="Imagem 02">
                        <img src="~/img/Uploads/@Model.Img02" alt="Imagem 02" class="img-small">
                    </a>
                    <div class="card-body">
                        <h6 class="card-title mb-1">Imagem 03</h6>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="block">
                    <a class="btn btn-warning"
                       asp-action="Edit"
                       asp-controller="Projeto"
                       asp-route-Id="@Model.ID">Editar projeto</a>
                </div>
            </div>
        </div>
    </div>
</section>

@section GalleryCss{
    <link href="~/lib/lightbox2/css/lightbox.min.css" rel="stylesheet" />
}

@section GalleryJS{
    <script src="~/lib/lightbox2/js/lightbox.min.js"></script>
}

MyPortfolio/Views/Projeto/Index.cshtml
@model ProjetoIndexViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section DataTableCss {
    <link href="~/lib/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" />
}

<div class="page-header no-margin-bottom">
    <div class="container-fluid">
        <h2 class="h5 no-margin-bottom">Projetos</h2>
    </div>
</div>
<div class="container-fluid">
    <ul class="breadcrumb">
        <li class="breadcrumb-item active">Projetos listar</li>
    </ul>
</div>
<section class="no-padding-top">
    <div class="container-fluid">
        <div class="block">
            @if (Model.PagedProjetos.Count > 0)
            {
                <div class="block-body">
                    <!-- Filtros -->
                    <div class="row mt-3 ml-2">
                        <div class="col-xs-3">
                            <div class="form-group">
                                <select class="custom-select" asp-for="FiltroId" asp-items="Model.ProjetoFiltro"></select>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <input class="form-control" type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                            </div>
                        </div>

                        <div class="col-xs-1">
                            <div class="form-group">
                                <button type="submit" class="btn btn-default form-control"><i class="fa fa-search"></i></button>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <button asp-action="Index" class="btn btn-light">Exibir todos</button>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table id="datatable1" style="width: 100%;" class="table">
                            <thead>
                                <tr>
                                    <th>Título</th>
                                    <th>Categoria</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var pro in Model.PagedProjetos)
                                {
                                    <tr>
                                        <td><a asp-action="Details" asp-route-Id="@pro.ID" class="text-muted">@pro.Titulo</a></td>
                                        <td>@pro.Tipo</td>
                                        <td align="right" valign="middle">
                                            <a asp-controller="Projeto"
                                               asp-action="Edit"
                                               asp-route-Id="@pro.ID"
                                               class="btn btn-warning"
                                               title="Editar Projeto">
                                                <i class="fa fa-wrench"></i>
                                            </a>
                                            <a asp-controller="Projeto"
                                               asp-action="Delete"
                                               asp-route-Id="@pro.ID"
                                               class="btn btn-danger" 
                                               title="Remover cadastro">
                                                <i class="fa fas fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer text-muted">
                        @{
                            var prevDisabled = !Model.PagedProjetos.HasPreviousPage ? "disabled" : "";
                            var nextDisabled = !Model.PagedProjetos.HasNextPage ? "disabled" : "";
                        }

                        <div class="col-lg-2">
                            <div class="d-inline-block flex-row ml-4 mb-4">
                                <a asp-action="Index"
                                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                                   asp-route-pageNumber="@(Model.PagedProjetos.PageIndex - 1)"
                                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                                   class="btn btn-light @prevDisabled">
                                    Voltar
                                </a>
                                <a asp-action="Index"
                                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                                   asp-route-pageNumber="@(Model.PagedProjetos.PageIndex + 1)"
                                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                                   class="btn btn-light @nextDisabled">
                                    Próximo
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="block-body text-center">
                    <div class="title"><strong>Você ainda não tem um projeto cadastrado</strong></div>
                    <div class="title"><a asp-action="Create" asp-controller="Projeto"> <b>ADICIONAR PROJETO</b></a></div>
                </div>
            }
        </div>
    </div>
</section>

@section DataTableJs {
    <script src="~/lib/datatables.net/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables.net-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/lib/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable1').DataTable({
                responsive: true,
                "columnDefs": [{
                    "targets": 4,
                    "orderable": false
                }],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Portuguese-Brasil.json"
                },
                "paging": false,
                "order": [[0, "desc"]],
            });

        });
    </script>
}